#!/bin/bash

# Script to setup tinc configurations for all nodes

set -e

BASE_DIR="/opt/gitrepo/vpn-experiments/tinc-vless/docker"
cd "$BASE_DIR/.."

echo "==============================================="
echo "  Setting up Tinc configurations"
echo "==============================================="
echo ""

# Create directory structure for each node
for node in node1 node2 node3; do
    echo "Setting up $node..."
    mkdir -p "docker/$node/tinc/hosts"
    mkdir -p "docker/$node/logs"
done

# Common VLESS UUID (all nodes share the same UUID for this test)
SHARED_UUID="a1b2c3d4-e5f6-7890-abcd-ef1234567890"

# Reality keys for the network
REALITY_PRIVATE_KEY="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
REALITY_PUBLIC_KEY="fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210"
REALITY_SHORT_ID="0123456789abcdef"
REALITY_DEST="www.google.com"

echo "Using shared UUID: $SHARED_UUID"
echo ""

# ============================================
# NODE 1 Configuration
# ============================================
echo "Configuring node1 (server)..."

cat > "docker/node1/tinc/tinc.conf" <<EOF
# Node1 - Main VLESS+Reality Server
Name = node1
Port = 655
DeviceType = tun
Interface = tinc0
Mode = router

# VLESS Configuration
VLESSMode = yes
VLESSUUID = $SHARED_UUID

# Reality Configuration
VLESSReality = yes
VLESSRealityDest = $REALITY_DEST
VLESSRealityDestPort = 443
VLESSRealityServerName = $REALITY_DEST
VLESSRealityPrivateKey = $REALITY_PRIVATE_KEY
VLESSRealityPublicKey = $REALITY_PUBLIC_KEY
VLESSRealityShortID = $REALITY_SHORT_ID
VLESSRealityFingerprint = chrome

# Network settings
PingInterval = 10
PingTimeout = 5
AutoConnect = yes
EOF

cat > "docker/node1/tinc/tinc-up" <<'EOF'
#!/bin/sh
ip link set $INTERFACE up
ip addr add 10.0.0.1/24 dev $INTERFACE
ip route add 10.0.0.0/24 dev $INTERFACE
echo "Node1 VPN interface configured: 10.0.0.1/24"
EOF

cat > "docker/node1/tinc/tinc-down" <<'EOF'
#!/bin/sh
ip route del 10.0.0.0/24 dev $INTERFACE
ip addr del 10.0.0.1/24 dev $INTERFACE
ip link set $INTERFACE down
echo "Node1 VPN interface down"
EOF

chmod +x "docker/node1/tinc/tinc-up" "docker/node1/tinc/tinc-down"

# ============================================
# NODE 2 Configuration
# ============================================
echo "Configuring node2 (client)..."

cat > "docker/node2/tinc/tinc.conf" <<EOF
# Node2 - VLESS+Reality Client
Name = node2
Port = 655
DeviceType = tun
Interface = tinc0
Mode = router

# Connect to node1
ConnectTo = node1

# VLESS Configuration
VLESSMode = yes
VLESSUUID = $SHARED_UUID

# Reality Configuration
VLESSReality = yes
VLESSRealityDest = $REALITY_DEST
VLESSRealityDestPort = 443
VLESSRealityServerName = $REALITY_DEST
VLESSRealityPrivateKey = $REALITY_PRIVATE_KEY
VLESSRealityPublicKey = $REALITY_PUBLIC_KEY
VLESSRealityShortID = $REALITY_SHORT_ID
VLESSRealityFingerprint = chrome

# Network settings
PingInterval = 10
PingTimeout = 5
AutoConnect = yes
EOF

cat > "docker/node2/tinc/tinc-up" <<'EOF'
#!/bin/sh
ip link set $INTERFACE up
ip addr add 10.0.0.2/24 dev $INTERFACE
ip route add 10.0.0.0/24 dev $INTERFACE
echo "Node2 VPN interface configured: 10.0.0.2/24"
EOF

cat > "docker/node2/tinc/tinc-down" <<'EOF'
#!/bin/sh
ip route del 10.0.0.0/24 dev $INTERFACE
ip addr del 10.0.0.2/24 dev $INTERFACE
ip link set $INTERFACE down
echo "Node2 VPN interface down"
EOF

chmod +x "docker/node2/tinc/tinc-up" "docker/node2/tinc/tinc-down"

# ============================================
# NODE 3 Configuration
# ============================================
echo "Configuring node3 (client)..."

cat > "docker/node3/tinc/tinc.conf" <<EOF
# Node3 - VLESS+Reality Client
Name = node3
Port = 655
DeviceType = tun
Interface = tinc0
Mode = router

# Connect to node1
ConnectTo = node1

# VLESS Configuration
VLESSMode = yes
VLESSUUID = $SHARED_UUID

# Reality Configuration
VLESSReality = yes
VLESSRealityDest = $REALITY_DEST
VLESSRealityDestPort = 443
VLESSRealityServerName = $REALITY_DEST
VLESSRealityPrivateKey = $REALITY_PRIVATE_KEY
VLESSRealityPublicKey = $REALITY_PUBLIC_KEY
VLESSRealityShortID = $REALITY_SHORT_ID
VLESSRealityFingerprint = chrome

# Network settings
PingInterval = 10
PingTimeout = 5
AutoConnect = yes
EOF

cat > "docker/node3/tinc/tinc-up" <<'EOF'
#!/bin/sh
ip link set $INTERFACE up
ip addr add 10.0.0.3/24 dev $INTERFACE
ip route add 10.0.0.0/24 dev $INTERFACE
echo "Node3 VPN interface configured: 10.0.0.3/24"
EOF

cat > "docker/node3/tinc/tinc-down" <<'EOF'
#!/bin/sh
ip route del 10.0.0.0/24 dev $INTERFACE
ip addr del 10.0.0.3/24 dev $INTERFACE
ip link set $INTERFACE down
echo "Node3 VPN interface down"
EOF

chmod +x "docker/node3/tinc/tinc-up" "docker/node3/tinc/tinc-down"

# ============================================
# Create Host Files (will be generated by tinc)
# ============================================
echo ""
echo "Creating placeholder host files..."

# Node1 host file
cat > "docker/node1/tinc/hosts/node1" <<EOF
Address = 172.20.0.10
Port = 655
Subnet = 10.0.0.1/32
EOF

# Node2 host file
cat > "docker/node2/tinc/hosts/node2" <<EOF
Address = 172.20.0.11
Port = 655
Subnet = 10.0.0.2/32
EOF

# Node3 host file
cat > "docker/node3/tinc/hosts/node3" <<EOF
Address = 172.20.0.12
Port = 655
Subnet = 10.0.0.3/32
EOF

# Cross-copy host files (each node needs to know about others)
for dest_node in node1 node2 node3; do
    for src_node in node1 node2 node3; do
        if [ "$dest_node" != "$src_node" ]; then
            cp "docker/$src_node/tinc/hosts/$src_node" "docker/$dest_node/tinc/hosts/"
        fi
    done
done

echo ""
echo "==============================================="
echo "  Configuration setup complete!"
echo "  Files created in docker/node*/ directories"
echo "==============================================="
echo ""
echo "Next steps:"
echo "  1. Build Docker image: cd docker && docker-compose build"
echo "  2. Start nodes: docker-compose up"
echo ""
